### ISSUE TITLE
(Metal) Screen goes white in build

### ISSUE THREAD

**Issue by coheebuzz** [CMDRSpirit/URPTemporalAA#8]
The effect works great in player, but when enabling the effect in the build the screen goes white.  Using Unity 2021.3.7.

Adding that i've already added the shader in the "Aways Include" list under Project Settings/Graphics, both Opaque and Depth textures are enabled and i am getting no console errors in the development build. 

![Screenshot 2022-11-29 at 9 52 05 PM](https://user-images.githubusercontent.com/11595730/204634860-d6b3eb60-23e9-4e41-9ef4-d1c9728ebb2d.png)

This is the only error i am getting:
![Screenshot 2022-11-30 at 1 49 40 AM](https://user-images.githubusercontent.com/11595730/204673798-dde0afab-9995-4ab4-958e-0e79be7a607c.png)

**Comment by CMDRSpirit** [comment]
Maybe you can try attaching the frame debugger to your build and see when the white image first occurs.
https://docs.unity3d.com/2021.3/Documentation/Manual/FrameDebugger.html

I also get a white screen when enabling MSAA, so make sure it is disabled in the build.
With MSAA enabled the frame debugger looks like this:
![image](https://user-images.githubusercontent.com/33422437/204805149-d078fa57-e4e6-4efc-ae1f-37fe055d10b0.png)
Unity inputs a white texture to the shader then.

For the effect to work, **MSAA has to be off** and the frame debugger should look like this:
![image](https://user-images.githubusercontent.com/33422437/204805644-55a99bef-de68-490a-ad35-7716758aa870.png)
If the `_MainTex` input is looking correct and the output is white, then we have a problem.

**Comment by coheebuzz** [comment]
Will do so and update you, i made sure MSAA is disabled both on camera and render settings.

From some more testing, the effects works in the build if i turn off "Post Processing" from the camera. However It does not work when i disable the Volume or individual PP effects.

**Comment by coheebuzz** [comment]
Here's what i am getting, it's not giving me any previews in any process so it's unrelated to this issue. 
![Screenshot 2022-11-30 at 3 56 25 PM](https://user-images.githubusercontent.com/11595730/204815040-279334c3-6eac-4a23-845f-149864f9717c.png)

Note that if i click on the "Render Post Processing Effects" process the image returns and is shaking due to the TAA effect, if that helps.

**Comment by CMDRSpirit** [comment]
Okay, it seems that `_MainTex` doesn't get set automatically.
What you can do is the following:
https://github.com/CMDRSpirit/URPTemporalAA/blob/f3d76211e3be09899346596c367d0570883de203/TemporalAA/TemporalAAFeature.cs#L127-L128

and add to line 128:
`TAAMaterial.SetTexture("_MainTex", renderingData.cameraData.renderer.cameraColorTargetHandle);`
I don't know if `cameraColorTargetHandle` is already present in your Unity version.

Alternative could be using
`cmd.SetGlobalTexture("_MainTex", renderingData.cameraData.renderer.cameraColorTarget);`
instead.

Hope this helps ;)

**Comment by coheebuzz** [comment]
None of those worked sadly, but i just got it to work by changing `AfterRenderingPostProcessing` to `BeforeRenderingPostProcessing`.

Not sure what other implications that might have but it looks ok.

**Comment by CMDRSpirit** [comment]
Oh okay, but these are good news.
`BeforeRenderingPostProcessing` is actually the correct way to implement TAA.
I wanted to change it for some time now, so maybe it was good that you got this issue ;)
