### ISSUE TITLE
URP 14.0.4 ScriptableRenderPass.Blit() is obsolete

### ISSUE THREAD

**Issue by cnkblgn** [CMDRSpirit/URPTemporalAA#9]
> Assets\Plugins\CMDRSpiritTAA\TemporalAAFeature.cs(135,13): warning CS0618: 'ScriptableRenderPass.Blit(CommandBuffer, RenderTargetIdentifier, RenderTargetIdentifier, Material, int)' is obsolete: 'Use RTHandles for source and destination'.

> Assets\Plugins\CMDRSpiritTAA\TemporalAAFeature.cs(136,30): warning CS0618: 'ScriptableRenderer.cameraColorTarget' is obsolete: 'Use cameraColorTargetHandle'

> Assets\Plugins\CMDRSpiritTAA\TemporalAAFeature.cs(136,13): warning CS0618: 'ScriptableRenderPass.Blit(CommandBuffer, RenderTargetIdentifier, RenderTargetIdentifier, Material, int)' is obsolete: 'Use RTHandles for source and destination'

This conversion works perfectly.

Blit(cmd, BuiltinRenderTextureType.CurrentActive, temp1, TAAMaterial);
=>
cmd.Blit(BuiltinRenderTextureType.CurrentActive, temp1, TAAMaterial);

Blit(cmd, temp1, renderingData.cameraData.renderer.cameraColorTarget);
=>
cmd.Blit(temp1, renderingData.cameraData.renderer.cameraColorTargetHandle);

**Comment by CMDRSpirit** [comment]
I am aware of this, but it would break compatibility with all URP versions < 13.1 and especially the Unity 2021 LTS version. They don't offer RTHandles of the camera ([See here](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@13.0/api/UnityEngine.Rendering.Universal.ScriptableRenderer.html)).
 As long as there is no problem with using those obsolete methods I would leave the code as it is.
